openapi: 3.2.0
info:
  title: Fhir Patient Access .well Known API
  description: '**Patient Access API for CMS 9115-F**


    To access the DentaQuest Patient Access API, a third-party application must obtain a valid JWT token by following the SMART on FHIR authorization framework.'
  version: v1
servers:
- url: https://api.dentaquest.com/FhirPatientAccess/v1
- url: https://api.deltadentalma.com/FhirPatientAccess/v1
tags:
- name: .well Known
paths:
  /.well-known/smart-configuration:
    get:
      summary: /.well-known/smart-configuration
      operationId: well-known-smart-configuration
      responses:
        '200':
          description: ''
      tags:
      - .well Known
